ifndef CONFIG_SITL_CF2
obj-$(CONFIG_PLATFORM_BOLT) += platform_bolt.o
obj-$(CONFIG_PLATFORM_CF2) += platform_cf2.o
obj-$(CONFIG_PLATFORM_TAG) += platform_tag.o
obj-$(CONFIG_PLATFORM_FLAPPER) += platform_flapper.o
obj-y += platform.o
obj-y += platform_stm32f4.o
obj-y += platform_utils.o
endif

ifdef CONFIG_SITL_CF2
obj-y += platform_sitl.o
endif
